export const sync24 = {
  pageInfo: { totalResults: 36972, resultsPerPage: 25 },
  regionCode: "UA",
  nextPageToken: "CBkQAA",
  items: [
    {
      id: "diQyhttl",
      image: "https://i.ytimg.com/vi/5z6IKnYXqFM/mqdefault.jpg",
      channelTitle: "The Psychedelic Muse",
      channelId: "UCAepXw94EhaO0CZV9f5D3fQ",
      itemId: "5z6IKnYXqFM",
      name: "Sync24 - Comfortable Void [Full Album]",
      itemType: "video",
    },
    {
      id: "35IlhYMd",
      image: "https://i.ytimg.com/vi/8ONz3_vjJIY/mqdefault.jpg",
      channelTitle: "The Psychedelic Muse",
      channelId: "UCAepXw94EhaO0CZV9f5D3fQ",
      itemId: "8ONz3_vjJIY",
      name: "Sync24 - Omnious [Full Album]",
      itemType: "video",
    },
    {
      id: "2g9a1nnq",
      image: "https://i.ytimg.com/vi/3QMvfdXRbm4/mqdefault.jpg",
      itemId: "PLrz8hHdG8-5BaFU3C8-klOA4L6ws-Lw_b",
      name: "Sync24 - Source | Leftfield Records [Full Album]",
      channelTitle: "Chill Space",
      channelId: "UCNHbHR2KOc851Kkb_TJ2Orw",
      itemType: "playlist",
    },
    {
      id: "I9FtYSFI",
      image: "https://i.ytimg.com/vi/jR5vexJSpv8/mqdefault.jpg",
      channelTitle: "The Psychedelic Muse",
      channelId: "UCAepXw94EhaO0CZV9f5D3fQ",
      itemId: "jR5vexJSpv8",
      name: "[Chill Space Mix Series 025] Sync24 - Summer Selection Mix",
      itemType: "video",
    },
    {
      id: "K7Lcyvu-",
      image: "https://i.ytimg.com/vi/kUEaGZd03dE/mqdefault.jpg",
      channelTitle: "The Psychedelic Muse",
      channelId: "UCAepXw94EhaO0CZV9f5D3fQ",
      itemId: "kUEaGZd03dE",
      name: "Sync24 - Acidious [Full Album]",
      itemType: "video",
    },
    {
      id: "yzHKUn2U",
      image: "https://i.ytimg.com/vi/vtZv-1tlgzA/mqdefault.jpg",
      channelTitle: "SYNC24",
      channelId: "UCrxV2H8jBQdBxIBjQIegKmw",
      itemId: "vtZv-1tlgzA",
      name: "SYNC24 - ACIDIOUS  | Album live preview in 360",
      itemType: "video",
    },
    {
      id: "1ktDPEe9",
      image: "https://i.ytimg.com/vi/joI6Dg1uNBY/mqdefault.jpg",
      channelTitle: "Psybrations",
      channelId: "UCEkBEbI7ME92qqjMjqvuIQA",
      itemId: "joI6Dg1uNBY",
      name: "SYNC24 - Dance of the Droids [Music Video]",
      itemType: "video",
    },
    {
      id: "ar3COwkt",
      image: "https://i.ytimg.com/vi/3mKbtXdgAYQ/mqdefault.jpg",
      channelTitle: "Scaran100",
      channelId: "UC2LArxdTecS6oIT1JELrnCg",
      itemId: "3mKbtXdgAYQ",
      name: "SYNC24 - Ambient Archive [ 1996-2002 ] full album",
      itemType: "video",
    },
    {
      id: "azC_fuwl",
      image: "https://i.ytimg.com/vi/LXx9nIxs5Nc/mqdefault.jpg",
      channelTitle: "ADDA",
      channelId: "UClQovQ0QLIP3bu9sp8RzUuw",
      itemId: "LXx9nIxs5Nc",
      name: "Sync24 - Something Something",
      itemType: "video",
    },
    {
      id: "DjvNpey3",
      image: "https://i.ytimg.com/vi/QYVRGOLR1eQ/mqdefault.jpg",
      channelTitle: "FOLD",
      channelId: "UCIRWmnDrZQeOprPJG9MFCeQ",
      itemId: "QYVRGOLR1eQ",
      name: "FOLD X Cultivated Electronics  // Sync24",
      itemType: "video",
    },
    {
      id: "RAd8k95V",
      image: "https://i.ytimg.com/vi/CNnkAWLpOFc/mqdefault.jpg",
      channelTitle: "Psychedelic Universe",
      channelId: "UCyRw5ZEQ2mVwNKq9GnSTHRA",
      itemId: "CNnkAWLpOFc",
      name: "Sync24 - Omnious (Full Album)",
      itemType: "video",
    },
    {
      id: "wGOUhm06",
      image: "https://i.ytimg.com/vi/gOi3FQ0R5fM/mqdefault.jpg",
      channelTitle: "Cosmic Soundwaves",
      channelId: "UC1PtAfzqXQJGvGCEMAwT30Q",
      itemId: "gOi3FQ0R5fM",
      name: "Sync24 - Ambient Archive [1996​-​2002] [Full Album]",
      itemType: "video",
    },
    {
      id: "v4wpJa5M",
      image: "https://i.ytimg.com/vi/pGPevV3z8Y4/mqdefault.jpg",
      channelTitle: "Savvas Kalt",
      channelId: "UClA7J-lgi0iOIB2PfNTxJSQ",
      itemId: "pGPevV3z8Y4",
      name: "SYNC24 - Wise Whispers In The Wind",
      itemType: "video",
    },
    {
      id: "uXxEdJjr",
      image: "https://i.ytimg.com/vi/_h4wUrIZWuU/mqdefault.jpg",
      channelTitle: "The Psychedelic Muse",
      channelId: "UCAepXw94EhaO0CZV9f5D3fQ",
      itemId: "_h4wUrIZWuU",
      name: "Sync24 - Eadgyth [Full EP]",
      itemType: "video",
    },
    {
      id: "bEzyPHLV",
      image: "https://i.ytimg.com/vi/c3s5j8owE3Q/mqdefault.jpg",
      channelTitle: "Chill Space",
      channelId: "UCNHbHR2KOc851Kkb_TJ2Orw",
      itemId: "c3s5j8owE3Q",
      name: "Sync24 - Spoon | Chill Space",
      itemType: "video",
    },
    {
      id: "JoaXypct",
      image: "https://i.ytimg.com/vi/RtkZDEOS1ZI/mqdefault.jpg",
      itemId: "PLrz8hHdG8-5BD-DPr3RgOTA_fRLH55zUD",
      name: "Sync24 - Comfortable Void | Leftfield Records [Full Album]",
      channelTitle: "Chill Space",
      channelId: "UCNHbHR2KOc851Kkb_TJ2Orw",
      itemType: "playlist",
    },
    {
      id: "UeP624U2",
      image: "https://i.ytimg.com/vi/44mR0n1BJiU/mqdefault.jpg",
      channelTitle: "atomicLogic",
      channelId: "UC4ZSbfPgb_YgywZG0xLbSTQ",
      itemId: "44mR0n1BJiU",
      name: "Sync24 - Source (album edit)",
      itemType: "video",
    },
    {
      id: "DyBbTerG",
      image: "https://i.ytimg.com/vi/SyFgq_9aqmE/mqdefault.jpg",
      channelTitle: "VGK MUSIC VIDEOS",
      channelId: "UCmFgjr8bOl2BWKMToR31ieQ",
      itemId: "SyFgq_9aqmE",
      name: "Sync24 - Cryptobiosis",
      itemType: "video",
    },
    {
      id: "6gRz7kcC",
      image: "https://i.ytimg.com/vi/4XglYW89WLQ/mqdefault.jpg",
      channelTitle: "Kalman Tibor",
      channelId: "UCjQWwlySJyXMEXtk9qNoIOg",
      itemId: "4XglYW89WLQ",
      name: "Sync24 - Cryptobiosis",
      itemType: "video",
    },
    {
      id: "HNnDRRtN",
      image: "https://i.ytimg.com/vi/z7S2iJmciwY/mqdefault.jpg",
      channelTitle: "skunkaholic",
      channelId: "UC8BZeqz97xnikQsHs2x6HGQ",
      itemId: "z7S2iJmciwY",
      name: "Sync24 - There Is No Spoon",
      itemType: "video",
    },
    {
      id: "r1csYdGb",
      image: "https://i.ytimg.com/vi/P0uyfhPGsu0/mqdefault.jpg",
      channelTitle: "Scaran100",
      channelId: "UC2LArxdTecS6oIT1JELrnCg",
      itemId: "P0uyfhPGsu0",
      name: "SYNC24 - 1N50MN14",
      itemType: "video",
    },
    {
      id: "OW36eYsw",
      image: "https://i.ytimg.com/vi/eUEvHKUq2OQ/mqdefault.jpg",
      channelTitle: "MoonHunter9",
      channelId: "UC_fQVmxqYgYdV4eQdv4VELA",
      itemId: "eUEvHKUq2OQ",
      name: "Sync24 - White Pixels",
      itemType: "video",
    },
    {
      id: "VsCwMTMA",
      image: "https://i.ytimg.com/vi/z4tvPOlSk4c/mqdefault.jpg",
      channelTitle: "Euphorhythm Music",
      channelId: "UCUwMatz3g6h9ikRU9yX7jHA",
      itemId: "z4tvPOlSk4c",
      name: "Sync24 - Feet in The Water",
      itemType: "video",
    },
    {
      id: "yH3H2bI1",
      image: "https://i.ytimg.com/vi/joI6Dg1uNBY/mqdefault.jpg",
      itemId: "PLwMyvxpePASLfdvo888nmkRKcMfmb7_Y5",
      name: "All Tracks - Sync24",
      channelTitle: " - Topic",
      channelId: "UCY47MeaUl148Q_0mJfbaufg",
      itemType: "playlist",
    },
    {
      id: "qlKh_DdB",
      image: "https://i.ytimg.com/vi/eq0VOM2fLMQ/mqdefault.jpg",
      channelTitle: "PSYlikon",
      channelId: "UCs2EGBc0-AqOj_iwJI0hMHg",
      itemId: "eq0VOM2fLMQ",
      name: "Sync24 - Dance Of The Droids",
      itemType: "video",
    },
  ],
};

export const jordanPeterson = {
  pageInfo: { totalResults: 1000000, resultsPerPage: 25 },
  regionCode: "UA",
  nextPageToken: "CBkQAA",
  items: [
    {
      id: "ueIZQCbV",
      image:
        "https://yt3.ggpht.com/aoJ9M6s2RCOH9-ULFs7ll9aS-viz4wj84VgdGmyJSkPdPySIZggg2nwyt5YGlLnfE5DTzt3J34s=s240-c-k-c0xffffffff-no-rj-mo",
      itemId: "UCL_f53ZEJxp8TtlOkHwMV9Q",
      name: "Jordan B Peterson",
      itemType: "channel",
    },
    {
      id: "AtQCUbN5",
      image: "https://i.ytimg.com/vi/Cn_lucBscH4/mqdefault.jpg",
      channelTitle: "Jordan B Peterson",
      channelId: "UCL_f53ZEJxp8TtlOkHwMV9Q",
      itemId: "Cn_lucBscH4",
      name: "Talking with Russians | The Jordan B. Peterson Podcast",
      itemType: "video",
    },
    {
      id: "7DbS5jH1",
      image: "https://i.ytimg.com/vi/0YUK3Jf-MGo/mqdefault.jpg",
      channelTitle: "Forever Inspired",
      channelId: "UCFCtCySYzCTd7PyOVVo2oiQ",
      itemId: "0YUK3Jf-MGo",
      name: 'Jordan Peterson - This Is GETTING OUT OF HAND!!"Enough Is Enough!"',
      itemType: "video",
    },
    {
      id: "Vcmlqu9T",
      image: "https://i.ytimg.com/vi/xu3ux1h_caU/mqdefault.jpg",
      channelTitle: "Jordan B Peterson",
      channelId: "UCL_f53ZEJxp8TtlOkHwMV9Q",
      itemId: "xu3ux1h_caU",
      name: "It's Time to Live",
      itemType: "video",
    },
    {
      id: "ve510Hl3",
      image: "https://i.ytimg.com/vi/UwTBbJlgYXA/mqdefault.jpg",
      channelTitle: "TheQuartering",
      channelId: "UCfwE_ODI1YTbdjkzuSi1Nag",
      itemId: "UwTBbJlgYXA",
      name: "Ethan Klein DESTROYED By Jordan Peterson After Trying To Cancel Him!",
      itemType: "video",
    },
    {
      id: "PmvAjwQu",
      image: "https://i.ytimg.com/vi/jKh0ni7HlNw/mqdefault.jpg",
      channelTitle: "Jordan B Peterson",
      channelId: "UCL_f53ZEJxp8TtlOkHwMV9Q",
      itemId: "jKh0ni7HlNw",
      name: "Evolution & the Challenges of Modern Life | Bret Weinstein & Heather Heying | The JBP Podcast S4 E73",
      itemType: "video",
    },
    {
      id: "VYBesOFZ",
      image: "https://i.ytimg.com/vi/yZYQpge1W5s/mqdefault.jpg",
      channelTitle: "British GQ",
      channelId: "UCUM0EMVw0nyynzUvwzO4vxQ",
      itemId: "yZYQpge1W5s",
      name: "Jordan Peterson: “There was plenty of motivation to take me out. It just didn't work\" | British GQ",
      itemType: "video",
    },
    {
      id: "7-hSJep1",
      image: "https://i.ytimg.com/vi/05wUtGMlDDg/mqdefault.jpg",
      channelTitle: "Motivation Madness",
      channelId: "UCHbq_l1qnuomfJCYQTsWf_Q",
      itemId: "05wUtGMlDDg",
      name: "Jordan Peterson's Speech Will Make You Wake Up In Life And Take Action | Motivation",
      itemType: "video",
    },
    {
      id: "6oOkTJ_H",
      image: "https://i.ytimg.com/vi/4O-UZGnv9O0/mqdefault.jpg",
      channelTitle: "OxfordUnion",
      channelId: "UCY7dD6waquGnKTZSumPMTlQ",
      itemId: "4O-UZGnv9O0",
      name: "Jordan Peterson: Imitation Of The Divine | Full Address and Q&A | Oxford Union",
      itemType: "video",
    },
    {
      id: "c6IgNUe-",
      image: "https://i.ytimg.com/vi/m9Njk8vpToQ/mqdefault.jpg",
      channelTitle: "Jordan B Peterson",
      channelId: "UCL_f53ZEJxp8TtlOkHwMV9Q",
      itemId: "m9Njk8vpToQ",
      name: "Jordan Peterson, God, and Christianity with Word on Fire | The JBP Podcast - S4: E69",
      itemType: "video",
    },
    {
      id: "ngyPdfHv",
      image: "https://i.ytimg.com/vi/ybDyMqfdzH4/mqdefault.jpg",
      channelTitle: "Be Inspired",
      channelId: "UCaKZDEMDdQc8t6GzFj1_TDw",
      itemId: "ybDyMqfdzH4",
      name: 'Jordan Peterson: "These Are Poisonous To Your Body” (this is why you are tired)',
      itemType: "video",
    },
    {
      id: "Vnk7SurZ",
      image: "https://i.ytimg.com/vi/qgYMuRqXPr0/mqdefault.jpg",
      channelTitle: "Jordan B Peterson",
      channelId: "UCL_f53ZEJxp8TtlOkHwMV9Q",
      itemId: "qgYMuRqXPr0",
      name: "Islam and the Possibility of Peace | Mohammed Hijab | The Jordan B. Peterson Podcast - S4: E66",
      itemType: "video",
    },
    {
      id: "yHHrIj_h",
      image: "https://i.ytimg.com/vi/GnpHlc8O_sY/mqdefault.jpg",
      channelTitle: "Jordan B Peterson",
      channelId: "UCL_f53ZEJxp8TtlOkHwMV9Q",
      itemId: "GnpHlc8O_sY",
      name: "Fortitude: American Resilience | Dan Crenshaw | The Jordan B. Peterson Podcast S4: E71",
      itemType: "video",
    },
    {
      id: "62255CzC",
      image: "https://i.ytimg.com/vi/aMcjxSThD54/mqdefault.jpg",
      channelTitle: "Channel 4 News",
      channelId: "UCTrQ7HXWRRxr7OsOtodr2_w",
      itemId: "aMcjxSThD54",
      name: "Jordan Peterson debate on the gender pay gap, campus protests and postmodernism",
      itemType: "video",
    },
    {
      id: "H1Rw3BBP",
      image: "https://i.ytimg.com/vi/vIeFt88Hm8s/mqdefault.jpg",
      channelTitle: "PowerfulJRE",
      channelId: "UCzQUP1qoWDoEbmsQxvdjxgQ",
      itemId: "vIeFt88Hm8s",
      name: "Joe Rogan Experience #1208 - Jordan Peterson",
      itemType: "video",
    },
    {
      id: "12cf4Myf",
      image: "https://i.ytimg.com/vi/5xbADDvciko/mqdefault.jpg",
      channelTitle: "Motivation Madness",
      channelId: "UCHbq_l1qnuomfJCYQTsWf_Q",
      itemId: "5xbADDvciko",
      name: "The Most Eye Opening 60 Minutes Of Your Life | Jordan Peterson Motivation",
      itemType: "video",
    },
    {
      id: "KPP9vZP3",
      image: "https://i.ytimg.com/vi/PYM-sS-0-yg/mqdefault.jpg",
      channelTitle: "Russell Howard",
      channelId: "UCnLxFpGiCi-u3RLx9uF8bOg",
      itemId: "PYM-sS-0-yg",
      name: "Jordan Peterson on Cancel Culture, Comedy, and His Battle With Depression  | The Russell Howard Hour",
      itemType: "video",
    },
    {
      id: "ymhJVSXT",
      image: "https://i.ytimg.com/vi/RazxNH5C2Zo/mqdefault.jpg",
      channelTitle: "Chaos & Order ",
      channelId: "UC7c5NhNnE--8-dnKurCUsXw",
      itemId: "RazxNH5C2Zo",
      name: "Jordan Peterson - FIX THIS and you'll GET a GIRLFRIEND",
      itemType: "video",
    },
    {
      id: "ao0ph6UP",
      image: "https://i.ytimg.com/vi/3enLBUJ5Od0/mqdefault.jpg",
      channelTitle: "Ben Shapiro",
      channelId: "UCnQC_G5Xsjhp9fEJKuIcrSw",
      itemId: "3enLBUJ5Od0",
      name: "Jordan Peterson's Thoughts on Transgenderism",
      itemType: "video",
    },
    {
      id: "sJwxdOG4",
      image: "https://i.ytimg.com/vi/DA-9y4laE5E/mqdefault.jpg",
      channelTitle: "Russell Brand",
      channelId: "UCswH8ovgUp5Bdg-0_JTYFNw",
      itemId: "DA-9y4laE5E",
      name: 'Jordan Peterson: "Any Regrets?"',
      itemType: "video",
    },
    {
      id: "egfC5yTB",
      image: "https://i.ytimg.com/vi/3uLDin9A9pc/mqdefault.jpg",
      channelTitle: "The Diary Of A CEO",
      channelId: "UCGq-a57w-aPwyi3pW7XLiHw",
      itemId: "3uLDin9A9pc",
      name: "Jordan Peterson: How To Become The Person You’ve Always Wanted To Be | E113",
      itemType: "video",
    },
    {
      id: "OgxzguvO",
      image: "https://i.ytimg.com/vi/miFwrdtTGqY/mqdefault.jpg",
      channelTitle: "Cambridge Union",
      channelId: "UClOuePXlJnw8-br7SXiuHqg",
      itemId: "miFwrdtTGqY",
      name: "Jordan Peterson | Cambridge Union",
      itemType: "video",
    },
    {
      id: "-QbJrC4E",
      image: "https://i.ytimg.com/vi/KZ-ArH19Kvs/mqdefault.jpg",
      channelTitle: "Jordan B Peterson",
      channelId: "UCL_f53ZEJxp8TtlOkHwMV9Q",
      itemId: "KZ-ArH19Kvs",
      name: "Why I Love Great Britain",
      itemType: "video",
    },
    {
      id: "bSdUhu6u",
      image: "https://i.ytimg.com/vi/q4zZ2ker1iI/mqdefault.jpg",
      channelTitle: "The Telegraph",
      channelId: "UCPgLNge0xqQHWM5B5EFH9Cg",
      itemId: "q4zZ2ker1iI",
      name: "Jordan Peterson: The collapse of our values is a greater threat than climate change | Off Script",
      itemType: "video",
    },
    {
      id: "WYzNULXb",
      image: "https://i.ytimg.com/vi/hQHigpiqUqE/mqdefault.jpg",
      channelTitle: "Hasanabi Moments",
      channelId: "UCobue-_fUPSIwdWULdE3MbQ",
      itemId: "hQHigpiqUqE",
      name: 'Jordan Peterson says "Just Work Harder" | Hasanabi Reacts',
      itemType: "video",
    },
  ],
};
